spin_manifest_version = 2

[application]
name = "app"
version = "0.1.0"
description = "Shared client and server data"

[[trigger.http]]
route = "/..."
component = "app"

[component.app]
source = "target/wasm32-wasi/release/app.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]

[component.app.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/client/..."
component = "client"

[component.client]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "client", destination = "/" }]
